- name: 创建filebeat-daemonset.yaml文件
  template: src=filebeat-daemonset.yaml dest={{ base_dir }}/manifests/filebeat-daemonset.yaml
  delegate_to: localhost
  
- name: 部署filebeat-daemonset.yaml
  shell: "{{bin_dir}}/kubectl apply -f {{ base_dir }}/manifests/filebeat-daemonset.yaml"
  delegate_to: localhost