version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /storage
  cache:
    layerinfo: inmemory
  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true
http:
  addr: :5000
  secret: placeholder
  debug:
    addr: localhost:5001
auth:
  token:
    issuer: harbor-token-issuer
    realm: http://localhost:6002/service/token
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry
notifications:
  endpoints:
    - name: harbor
      disabled: false
      url: http://localhost:6002/service/notifications
      timeout: 3000ms
      threshold: 5
      backoff: 1s
