## ---------docker daemon配置部分-----------
- name: 下载 docker 二进制文件
  copy: src={{ base_dir }}/bin/docker/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - docker-containerd
  - docker-containerd-shim
  - docker-init
  - docker-runc
  - docker
  - docker-containerd-ctr
  - dockerd
  - docker-proxy
  
- name: docker国内镜像加速
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json

- name: 创建docker的systemd unit文件
  template: src=docker.service.j2 dest=/etc/systemd/system/docker.service

- name: 创建docker的systemd unit文件
  template: src=docker.service.j2 dest=/etc/systemd/system/docker.service

- name: restart service docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
    enabled: yes

- name: 轮询等待docker启动
  shell: "systemctl status docker.service|grep Active"
  register: docker_status
  until: '"running" in docker_status.stdout'
  retries: 8
  delay: 2
  when: not ansible_check_mode