- name: 引入ccapi变量
  include_vars: "{{base_dir}}/roles/gpaas/cs-cloud/auth/defaults/main.yml"

- name: 引入alert变量
  include_vars: "{{base_dir}}/roles/gpaas/monitor/alert/defaults/main.yml"
  
- name: 引入inspect变量
  include_vars: "{{base_dir}}/roles/gpaas/monitor/inspect/defaults/main.yml"
  
- name: 引入push变量
  include_vars: "{{base_dir}}/roles/gpaas/monitor/push/defaults/main.yml"

- name: 创建目录
  file: name={{ base_dir }}/manifests/cs-cloud state=directory

- block:
  - name: 创建cs-mysql.yaml文件
    template: src=cs-mysql.yaml dest={{ base_dir }}/manifests/cs-cloud/cs-mysql.yaml
  - name: 部署cs-mysql.yaml
    shell: "{{bin_dir}}/kubectl apply -f {{ base_dir }}/manifests/cs-cloud/cs-mysql.yaml"
  when: cs_external_db == false

- name: 创建 ccapi yaml文件
  template: src=ccapi.yaml dest={{ base_dir }}/manifests/cs-cloud/ccapi.yaml
  
- name: 部署 ccapi
  shell: "{{bin_dir}}/kubectl apply -f {{ base_dir }}/manifests/cs-cloud/ccapi.yaml"
 
- name: 创建 zipkin yaml文件
  template: src=zipkin-server.yaml dest={{ base_dir }}/manifests/cs-cloud/zipkin-server.yaml
  
- name: 部署 zipkin
  shell: "{{bin_dir}}/kubectl apply -f {{ base_dir }}/manifests/cs-cloud/zipkin-server.yaml"

  
- block:
  - name: 创建gitlab.yaml文件
    template: src=gitlab.yaml dest={{ base_dir }}/manifests/cs-cloud/gitlab.yaml
  - name: 部署gitlab.yaml
    shell: "{{bin_dir}}/kubectl apply -f {{ base_dir }}/manifests/cs-cloud/gitlab.yaml"
  when: gitlab_enable == true