- name: 下载 metricbeat rpm文件
  copy: src={{ base_dir }}/rpm/elk/metricbeat-6.2.3-x86_64.rpm dest=/opt/metricbeat-6.2.3-x86_64.rpm mode=0755

- name: 安装 metricbeat 包
  shell: cd /opt && rpm -ivh metricbeat-6.2.3-x86_64.rpm

- name: 将metricbeat服务设置为开机启动
  shell: chkconfig metricbeat on

- name: 创建 metricbeat.yml文件
  template: src=metricbeat.yml.conf dest=/etc/metricbeat/metricbeat.yml
  
- name: 创建目录prospectors.d
  file: name=/etc/metricbeat/prospectors.d state=directory

- name: 创建system.yml文件
  template: src=system.yml.conf dest=/etc/metricbeat/prospectors.d/system.yml  
  
- name: 创建docker.yml文件
  template: src=docker.yml.conf dest=/etc/metricbeat/prospectors.d/docker.yml
  
- name: 创建kubernetes.yml文件
  template: src=kubernetes.yml.conf dest=/etc/metricbeat/prospectors.d/kubernetes.yml  
  
- name: start-metricbeat
  shell: systemctl start metricbeat
  