apiVersion: v1
kind: Endpoints
metadata:
  name: heketi-storage-endpoints
  namespace: kube-system
subsets:
- addresses:
{%- for node in groups['kube-storage-node'] -%}
  - ip: {{ node}}
{%- endfor -%}
  ports:
  - name: glusterfs
    port: 1