k8s_calico_image: "k8s/node:v2.6.7"
k8s_cni_image: "k8s/cni:v1.11.2"
k8s_calico_controllers_image: "k8s/kube-controllers:v1.0.3"
k8s_dns_image: "k8s/k8s-dns-kube-dns-amd64:1.14.8"
k8s_dnsmasq_image: "k8s/k8s-dns-dnsmasq-nanny-amd64:1.14.8"
k8s_dnssidecar_image: "k8s/k8s-dns-sidecar-amd64:1.14.8"
k8s_dashboard_image: "k8s/kubernetes-dashboard-amd64:v1.8.3"
k8s_traefik_image: "k8s/traefik:1.5"
k8s_heapster_image: "k8s/heapster-amd64:v1.5.0"
k8s_addon_resizer_image: "k8s/addon-resizer:1.7"
k8s_influxdb_image: "k8s/heapster-influxdb-amd64:v1.3.3"
k8s_grafana_image: "k8s/heapster-grafana-amd64:v4.4.3"
k8s_kube_proxy_image: "k8s/kube-proxy:v1.10.2"
#glusterfs
k8s_gluster_image: k8s/gluster-centos:3.13.2
k8s_heketi_image: k8s/heketi:6.0

#非必选镜像
k8s_metrics_server_image: "k8s/metrics-server-amd64:v0.2.0"
#k8s_cluster_proportional_autoscaler_image=k8s/cluster-proportional-autoscaler-amd64:1.1.2
k8s_node_problem_detector_image: "k8s/node-problem-detector:v0.4.1"
kube_state_metrics_image: k8s/kube-state-metrics:v1.4.0

#openvpn
openvpn_image: base/openvpn:3.1

#资源请求值与限制值
calico_node_cpu_requests:  50m
calico_node_cpu_limit: 500m
calico_node_mem_requests: 100Mi
calico_node_mem_limit: 800Mi

calico_controllers_cpu_requests:  100m
calico_controllers_cpu_limit: 150m
calico_controllers_mem_requests: 40Mi
calico_controllers_mem_limit: 100Mi

kubeproxy_cpu_requests:  50m
kubeproxy_cpu_limit: 200m
kubeproxy_mem_requests: 50Mi
kubeproxy_mem_limit: 400Mi

kubedns_cpu_requests:  10m
kubedns_cpu_limit: 200m
kubedns_mem_requests: 20Mi
kubedns_mem_limit: 500Mi

heapster_cpu_requests: 50m
heapster_cpu_limit: 100m
heapster_mem_requests: 90Mi
heapster_mem_limit: 128Mi

kubedashboard_cpu_requests:  50m
kubedashboard_cpu_limit: 100m
kubedashboard_mem_requests: 200Mi
kubedashboard_mem_limit: 300Mi

traefik_cpu_requests:  250m
traefik_cpu_limit: 500m
traefik_mem_requests: 60Mi
traefik_mem_limit: 800Mi

grafana_cpu_requests:  100m
grafana_cpu_limit: 100m
grafana_mem_requests: 100Mi
grafana_mem_limit: 100Mi

kube_state_metrics_cpu_requests:  200m
kube_state_metrics_cpu_limit: 500m
kube_state_metrics_mem_requests: 100Mi
kube_state_metrics_mem_limit: 200Mi

openvpn_cpu_requests:  30m
openvpn_cpu_limit: 100m
openvpn_mem_requests: 10Mi
openvpn_mem_limit: 200Mi

glusterfs_cpu_limit: >-
  {{hostvars[groups["kube-storage-node"][0]].ansible_processor_vcpus * 1000 * 0.65}}m
glusterfs_cpu_requests: >-
  {{hostvars[groups["kube-storage-node"][0]].ansible_processor_vcpus * 1000 * 0.65}}m

glusterfs_mem_limit: >-
  {{(hostvars[groups["kube-storage-node"][0]].ansible_memtotal_mb * 0.625)|int}}Mi
glusterfs_mem_requests: >-
  {{(hostvars[groups["kube-storage-node"][0]].ansible_memtotal_mb * 0.625)|int}}Mi

heketi_cpu_requests:  10m
heketi_cpu_limit: 100m
heketi_mem_requests: 100Mi
heketi_mem_limit: 250Mi
