apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: monitor-service
  labels:
    app: monitor-service
  name: monitor-service
  namespace: uimp-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-service
  template:
    metadata:
      labels:
        app: monitor-service
    spec:
      containers:
      - image: {{BASE_IMAGE_URL}}/{{cs_monitor_backend_image}}
        name: monitor-service-container1
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        env:
        - name: spring_datasource_url
          value: "jdbc:mysql://{{cs_db_host}}:{{cs_db_port}}/{{cs_monitor_db_name}}?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8"
        - name: spring_datasource_username
          value: "{{cs_monitor_db_username}}"
        - name: spring_datasource_password
          value: "{{cs_monitor_db_passwd}}"
        - name: alert_ccapi_api
          value: "{{cs_monitor_ccapi_api}}"
        - name: alert_es
          value: "{{cs_monitor_es}}"
        - name: alert_push_api
          value: "{{cs_monitor_push_api}}"
        - name: alert_datasource_elasticsearch_authorityFlag
          value: "false"
        ports:
        - containerPort: 8081
          protocol: TCP
        volumeMounts:
        - mountPath: /applogs
          name: monitor-volume-elk-log
      volumes:
      - hostPath:
          path: /data/log
          type: ""
        name: monitor-volume-elk-log
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitor-service
  name: monitor-service
  namespace: uimp-cloud
spec:
  ports:
  - name: port1
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: monitor-service
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/proxy-body-size: 1000m
  name: monitor-service
  namespace: uimp-cloud
spec:
  rules:
  - host: {{cs_monitor_backend_ingress}}
    http:
      paths:
      - backend:
          serviceName: monitor-service
          servicePort: 8081
        path: /