#节点角色
node_role: >-
  {%-if "harbor" in group_names -%}lb
  {%-elif "lb" in group_names -%}lb
  {%-elif "kube-master" in group_names -%}master
  {%-else-%}compute
  {%-endif-%}
#kubelet 工作目录
kubelet_dir: >-
 {{data_dir}}/kubelet
max_pods: 110
