k8s_apiserver_image: toyangdon/kube-apiserver-arm64:v1.16.4
k8s_scheduler_image: toyangdon/kube-scheduler-arm64:v1.16.4
k8s_controller_image: toyangdon/kube-controller-manager-arm64:v1.16.4
k8s_etcd_image: toyangdon/etcd:v3.4.0-arm64

#资源请求值与限制值
#apiserver_cpu_requests: 1000m
#apiserver_cpu_limit: 1000m
#apiserver_mem_requests: 2Gi
#apiserver_mem_limit: 2Gi

apiserver_cpu_limit: >-
  {{ansible_processor_vcpus * 1000 * 0.25}}m
apiserver_cpu_requests: >-
  {{ansible_processor_vcpus * 1000 * 0.25}}m

apiserver_mem_limit: >-
  {{(ansible_memtotal_mb * 0.32)|int}}Mi
apiserver_mem_requests: >-
  {{(ansible_memtotal_mb * 0.32)|int}}Mi

#controller_manager_cpu_requests: 500m
#controller_manager_cpu_limit: 500m
#controller_manager_mem_requests: 1Gi
#controller_manager_mem_limit: 1Gi

controller_manager_cpu_limit: >-
  {{ansible_processor_vcpus * 1000 * 0.125}}m
controller_manager_cpu_requests: >-
  {{ansible_processor_vcpus * 1000 * 0.125}}m

controller_manager_mem_limit: >-
  {{(ansible_memtotal_mb * 0.125)|int}}Mi
controller_manager_mem_requests: >-
  {{(ansible_memtotal_mb * 0.125)|int}}Mi

#scheduler_cpu_requests: 500m
#scheduler_cpu_limit: 500m
#scheduler_mem_requests: 1Gi
#scheduler_mem_limit: 1Gi

scheduler_cpu_limit: >-
  {{ansible_processor_vcpus * 1000 * 0.05}}m
scheduler_cpu_requests: >-
  {{ansible_processor_vcpus * 1000 * 0.05}}m

scheduler_mem_limit: >-
  {{(ansible_memtotal_mb * 0.0625)|int}}Mi
scheduler_mem_requests: >-
  {{(ansible_memtotal_mb * 0.0625)|int}}Mi

#etcd_cpu_requests: 500m
#etcd_cpu_limit: 500m
#etcd_mem_requests: 1Gi
#etcd_mem_limit: 1Gi

etcd_cpu_limit: >-
  {{ansible_processor_vcpus * 1000 * 0.2}}m
etcd_cpu_requests: >-
  {{ansible_processor_vcpus * 1000 * 0.2}}m

etcd_mem_limit: >-
  {{(ansible_memtotal_mb * 0.125)|int}}Mi
etcd_mem_requests: >-
  {{(ansible_memtotal_mb * 0.125)|int}}Mi


#etcd配置
ETCD_ELECTION_TIMEOUT: 5000
ETCD_HEARTBEAT_INTERVAL: 250