- hosts:
  - elasticsearch
  roles:
  - kubernetes/prepare
  - kubernetes/docker
  - { role: kubernetes/calico , when: "CLUSTER_NETWORK == 'calico'" }
  - { role: kubernetes/flannel, when: "CLUSTER_NETWORK == 'flannel'" }
  - kubernetes/kube-node
  - gpaas/elk/elasticsearch 