- name: 创建flannel cni 相关目录
  file: name={{ item }} state=directory
  with_items:
  - /etc/cni/net.d
  - /root/local/kube-system/flannel

- name: 下载flannel cni plugins
  copy: src={{ base_dir }}/bin/cni/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - bridge
  - flannel
  - host-local
  - loopback
  - portmap
  
# 删除原有cni配置
- name: 删除默认cni配置 
  file: path=/etc/cni/net.d/10-default.conf state=absent