# prepare
- hosts: deploy
  tasks:
  - name: 创建uimpcloud命名空间
    shell: "{{bin_dir}}/kubectl create ns uimp-cloud"
    ignore_errors: true

# 插件部署
- hosts: deploy
  roles:
  - gpaas/cs-cloud/ccapi
  - gpaas/cs-cloud/auth
  - gpaas/cs-cloud/dashboard