apiVersion: v1
kind: Pod
metadata:
  name: harbor
  namespace: kube-system
  labels:
    name: harbor    
spec:
  hostNetwork: true
  containers:
  - name: ui-app
    image: {{BASE_IMAGE_URL}}/{{harbor_ui_image}}
    imagePullPolicy: IfNotPresent
    env:
    - name: CONFIG_PATH
      value: "/etc/ui/app.conf"
    - name: LOG_LEVEL
      value: "error"
    - name: GODEBUG
      value: "netdns=cgo"
    - name: ADMIN_SERVER_URL
      value: http://localhost:81
    ports:
    - containerPort: 6002
    resources:
      requests:
        cpu: {{ harbor_ui_cpu_requests }}
        memory: {{ harbor_ui_mem_requests }}
      limits:
        cpu: {{ harbor_ui_cpu_limit }}
        memory: {{ harbor_ui_mem_limit }}
    volumeMounts:
    - name: ui-config
      mountPath: /etc/ui
  - name: registry-app
    image: {{BASE_IMAGE_URL}}/{{harbor_registry_image}}
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000
    - containerPort: 5001
    resources:
      requests:
        cpu: {{ harbor_registry_cpu_requests }}
        memory: {{ harbor_registry_mem_requests }}
      limits:
        cpu: {{ harbor_registry_cpu_limit }}
        memory: {{ harbor_registry_mem_limit }}
    volumeMounts:
    - name: registry-config
      mountPath: /etc/registry
    - name: storage
      mountPath: /storage
  - name: mysql-app
    image: {{BASE_IMAGE_URL}}/{{harbor_db_image}}
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "root"
    resources:
      requests:
        cpu: {{ harbor_mysql_cpu_requests }}
        memory: {{ harbor_mysql_mem_requests }}
      limits:
        cpu: {{ harbor_mysql_cpu_limit }}
        memory: {{ harbor_mysql_mem_limit }}
    volumeMounts:
    - name: mysql-storage
      mountPath: /var/lib/mysql
  - name: adminserver-app
    image: {{BASE_IMAGE_URL}}/{{harbor_adminserver_image}}
    imagePullPolicy: IfNotPresent
    env:
      - name: LOG_LEVEL
        value: "error"
      - name: JSON_CFG_STORE_PATH
        value: "/etc/config/config.json"
      - name: EXT_ENDPOINT
        value: "http://{{harbor_ext_endpoint}}"
      - name: AUTH_MODE
        value: "db_auth"
      - name: SELF_REGISTRATION
        value: "on"
      - name: DATABASE_TYPE
        value: "mysql"
      - name: MYSQL_HOST
        value: "localhost"
      - name: MYSQL_PORT
        value: "3306"
      - name: PORT
        value: "81"
      - name: MYSQL_USR
        value: "root"
      - name: MYSQL_PWD
        value: "root"
      - name: MYSQL_DATABASE
        value: "registry"
      - name: REGISTRY_URL
        value: "http://localhost:5000"
      - name: TOKEN_SERVICE_URL
        value: "http://{{harbor_ext_endpoint}}:6002/service/token"
      - name: HARBOR_ADMIN_PASSWORD
        value: "{{harbor_admin_password}}"
      - name: PROJECT_CREATION_RESTRICTION
        value: "everyone"
      - name: VERIFY_REMOTE_CERT
        value: "on"
      - name: MAX_JOB_WORKERS
        value: "10"
      - name: TOKEN_EXPIRATION
        value: "30"
      - name: CFG_EXPIRATION
        value: "5"
      - name: GODEBUG
        value: "netdns=cgo"
      - name: ADMIRAL_URL
        value: "NA"
      - name: WITH_NOTARY
        value: "false"
      - name: RESET
        value: "false"
      - name: IMAGE_STORE_PATH
        value: "/"
    ports:
    - containerPort: 81
    resources:
      requests:
        cpu: {{ harbor_adminserver_cpu_requests }}
        memory: {{ harbor_adminserver_mem_requests }}
      limits:
        cpu: {{ harbor_adminserver_cpu_limit }}
        memory: {{ harbor_adminserver_mem_limit }}
    volumeMounts:
    - name: adminserver-config
      mountPath: /etc/adminserver/
  - name: nginx-app
    image: {{BASE_IMAGE_URL}}/{{harbor_nginx_image}}
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    - containerPort: 443
    resources:
      requests:
        cpu: {{ harbor_nginx_cpu_requests }}
        memory: {{ harbor_nginx_mem_requests }}
      limits:
        cpu: {{ harbor_nginx_cpu_limit }}
        memory: {{ harbor_nginx_mem_limit }}
    volumeMounts:
    - name: config
      mountPath: /etc/nginx
  volumes:
  - name: config
    hostpath: 
      path: /data/harbor/nginx
  - name: adminserver-config
    hostpath: 
      path: /data/harbor/adminserver
  - name: ui-config
    hostpath: 
      path: /data/harbor/ui 
  - name: registry-config
    hostpath: 
      path: /data/harbor/registry/config
  - name: storage
    hostpath: 
      path: /data/harbor/registry/storage	
  - name: mysql-storage
    hostpath: 
      path: /data/harbor/mysql
      type: DirectoryOrCreate